# Markdown generation utilities (internal)
#
# Functions for generating markdown documentation from lib metadata.
#
{ lib }:
let
  # Generate markdown anchor from lib name
  nameToAnchor = name: builtins.replaceStrings [ "." ] [ "-" ] name;

  # Generate index entry for a single lib
  libToIndexEntry =
    name: meta:
    let
      anchor = nameToAnchor name;
      fileLink = if meta.file or null != null then " ([source](${meta.file}))" else "";
    in
    "- [`${name}`](#${anchor})${fileLink}";

  # Generate markdown for a single lib
  libToMarkdown =
    name: meta:
    let
      anchor = nameToAnchor name;
      visibleStr = if meta.visible or true then "" else " *(private)*";
      descStr = meta.description or "No description";
      testCount = builtins.length (builtins.attrNames (meta.tests or { }));
      testsStr = if testCount > 0 then " (${toString testCount} tests)" else "";
      fileStr =
        if meta.file or null != null then
          ''

            **Source:** [${meta.file}](${meta.file})
          ''
        else
          "";
      exampleStr =
        if meta.example or null != null then
          ''

            **Example:**
            ```nix
            ${meta.example}
            ```
          ''
        else
          "";
    in
    ''
      ### `${name}` {#${anchor}}${visibleStr}

      ${descStr}${testsStr}
      ${fileStr}${exampleStr}
    '';

  # Generate full markdown document
  generateMarkdown =
    allLibsMeta:
    let
      allSortedLibNames = builtins.sort (a: b: a < b) (builtins.attrNames allLibsMeta);
      indexEntries = lib.concatMapStringsSep "\n" (
        name: libToIndexEntry name allLibsMeta.${name}
      ) allSortedLibNames;
      libDocs = lib.concatMapStrings (name: libToMarkdown name allLibsMeta.${name}) allSortedLibNames;
      libCount = builtins.length allSortedLibNames;
    in
    ''
      # nix-lib API Reference

      Generated documentation for all defined library functions.

      **Total libs:** ${toString libCount}

      ## Index

      ${indexEntries}

      ## Libraries

      ${libDocs}
      ---

      *Generated by nix-lib*
    '';
in
{
  inherit
    nameToAnchor
    libToIndexEntry
    libToMarkdown
    generateMarkdown
    ;
}
